### ISSUE TITLE
run on save not working

### ISSUE THREAD

**Issue by igregson** [dmnsgn/sublime-stylefmt#17]
Have set `"formatOnSave": true` in both the default and user settings... 

Using the latest version, 4.3.2

**Comment by dmnsgn** [comment]
Is the file you are trying to save using either `CSS` or `SCSS` syntax? If not you might want to have a look at the `"scssSyntax"` option.

**Comment by igregson** [comment]
Yes, they are `.scss` files.

**Comment by dmnsgn** [comment]
File extension and file syntax are two different things. This plugin checks the file syntax (indicated in the bottom right corner of ST) in order to determine if it should run on save: https://github.com/dmnsgn/sublime-stylefmt/blob/master/Stylefmt.py#L24

Unless there is an error in your ST console, format on save cannot be triggered if the file syntax setting is wrong.

**Comment by igregson** [comment]
Ahh... that was it. My syntax is set to Sass. Updating this in the config did the trick.

Thank you!
